import { VislabMount } from "@vislab/react";
import type { VislabComponentEntry, VislabPropSchema } from "@vislab/registry";
import { vislabRegistry } from "@vislab/registry";
import React, { useCallback, useEffect, useMemo, useState } from "react";

type ExportTab = "mdx" | "html" | "jekyll" | "iframe";

function buildMdxSnippet(
  entry: VislabComponentEntry,
  props: Record<string, unknown>,
): string {
  const propsParts = Object.entries(props).filter(
    ([, v]) => v !== undefined && v !== "",
  );
  const jsxProps =
    propsParts.length > 0
      ? " " +
        propsParts
          .map(([k, v]) => {
            if (typeof v === "string") return `${k}=${JSON.stringify(v)}`;
            return `${k}={${JSON.stringify(v)}}`;
          })
          .join(" ")
      : "";
  return `import { ${entry.globalName} } from '@vislab/react';

<${entry.globalName} client:visible${jsxProps} />
`;
}

function buildHtmlSnippet(
  entry: VislabComponentEntry,
  props: Record<string, unknown>,
): string {
  const filtered = Object.fromEntries(
    Object.entries(props).filter(([, v]) => v !== undefined && v !== ""),
  );
  const hasProps = Object.keys(filtered).length > 0;
  return `<div
  data-vislab="${entry.globalName}"${
    hasProps ? `\n  data-props='${JSON.stringify(filtered)}'` : ""
  }
  style="min-height: 420px; width: 100%;"
></div>
<!-- Requires vislab-embed.min.js in page head -->`;
}

function buildJekyllSnippet(
  entry: VislabComponentEntry,
  props: Record<string, unknown>,
): string {
  const filtered = Object.fromEntries(
    Object.entries(props).filter(([, v]) => v !== undefined && v !== ""),
  );
  const propsAttr =
    Object.keys(filtered).length > 0
      ? ` props='${JSON.stringify(filtered)}'`
      : "";
  return `{% include vislab.html id="${entry.id}" component="${entry.globalName}"${propsAttr} %}`;
}

function buildIframeSnippet(entry: VislabComponentEntry): string {
  // Generated by: pnpm --filter @vislab/cli exec vislab widget -c <Name> -o ./public/vizlab
  // Host the folder and point src at your CDN/static origin.
  return `<!-- 1) Generate: pnpm --filter @vislab/cli exec vislab widget -c ${entry.globalName} -o ./public/vizlab -->
<!-- 2) Deploy ./public/vizlab and set YOUR_ORIGIN to your site origin -->
<iframe
  src="YOUR_ORIGIN/vizlab/${entry.globalName.toLowerCase()}/index.html"
  title="${entry.displayName}"
  style="width: 100%; min-height: 480px; border: 1px solid #1e293b;"
  loading="lazy"
></iframe>`;
}

function parsePropValue(schema: VislabPropSchema, raw: string): unknown {
  if (schema.type === "boolean") return raw === "true";
  if (schema.type === "number") {
    const n = Number(raw);
    return Number.isFinite(n) ? n : undefined;
  }
  if (schema.type === "string[]") {
    return raw
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  }
  return raw;
}

function formatPropValue(
  value: unknown,
  type: VislabPropSchema["type"],
): string {
  if (value === undefined) return "";
  if (type === "string[]" && Array.isArray(value)) return value.join(",");
  if (type === "boolean") return value ? "true" : "false";
  return String(value);
}

function PropertyField({
  schema,
  value,
  onChange,
}: {
  schema: VislabPropSchema;
  value: unknown;
  onChange: (v: unknown) => void;
}) {
  const id = `prop-${schema.name}`;
  if (schema.type === "boolean") {
    return (
      <label className="flex items-center gap-2 text-sm text-slate-300">
        <input
          id={id}
          type="checkbox"
          checked={Boolean(value)}
          onChange={(e) => onChange(e.target.checked)}
          className="rounded border-slate-600"
        />
        {schema.name}
      </label>
    );
  }
  return (
    <div className="flex flex-col gap-1.5">
      <label htmlFor={id} className="text-xs font-semibold text-slate-400">
        {schema.name}
        {schema.optional && (
          <span className="text-slate-600 font-normal"> (optional)</span>
        )}
      </label>
      {schema.description && (
        <span className="text-[10px] text-slate-600">{schema.description}</span>
      )}
      <input
        id={id}
        type={schema.type === "number" ? "number" : "text"}
        value={formatPropValue(value, schema.type)}
        onChange={(e) => onChange(parsePropValue(schema, e.target.value))}
        className="bg-slate-800 border border-slate-700 rounded-md px-3 py-2 text-sm text-slate-200 font-mono"
      />
    </div>
  );
}

export default function StudioWorkbench() {
  const [selectedId, setSelectedId] = useState(() => {
    if (typeof window === "undefined") return vislabRegistry[0]?.id ?? "";
    const p = new URLSearchParams(window.location.search);
    return p.get("component") ?? vislabRegistry[0]?.id ?? "";
  });
  const [propValues, setPropValues] = useState<Record<string, unknown>>({});
  const [exportTab, setExportTab] = useState<ExportTab>("mdx");
  const [exportMsg, setExportMsg] = useState<string | null>(null);

  const entry = useMemo(
    () => vislabRegistry.find((e) => e.id === selectedId),
    [selectedId],
  );

  useEffect(() => {
    if (!entry?.props) {
      setPropValues({});
      return;
    }
    const fromUrl =
      typeof window !== "undefined"
        ? new URLSearchParams(window.location.search)
        : null;
    const initial: Record<string, unknown> = {};
    for (const p of entry.props) {
      const urlVal = fromUrl?.get(p.name);
      if (urlVal != null) {
        initial[p.name] = parsePropValue(p, urlVal);
      } else if (p.name === "stages" && p.type === "string[]") {
        initial[p.name] = ["IF", "ID", "EX", "MEM", "WB"];
      } else if (p.name === "autoPlay" && p.type === "boolean") {
        initial[p.name] = true;
      }
    }
    setPropValues(initial);
  }, [entry]);

  useEffect(() => {
    if (typeof window === "undefined" || !entry) return;
    const params = new URLSearchParams();
    params.set("component", entry.id);
    for (const schema of entry.props ?? []) {
      const v = propValues[schema.name];
      if (v !== undefined && v !== "")
        params.set(schema.name, formatPropValue(v, schema.type));
    }
    const next = `${window.location.pathname}?${params.toString()}`;
    window.history.replaceState({}, "", next);
  }, [entry, propValues]);

  const previewProps = useMemo(() => {
    const out: Record<string, unknown> = {};
    for (const schema of entry?.props ?? []) {
      const v = propValues[schema.name];
      if (v !== undefined && v !== "") out[schema.name] = v;
    }
    return out;
  }, [entry, propValues]);

  const exportSnippet = useMemo(() => {
    if (!entry) return "";
    switch (exportTab) {
      case "mdx":
        return buildMdxSnippet(entry, previewProps);
      case "html":
        return buildHtmlSnippet(entry, previewProps);
      case "jekyll":
        return buildJekyllSnippet(entry, previewProps);
      case "iframe":
        return buildIframeSnippet(entry);
    }
  }, [entry, exportTab, previewProps]);

  const propsKey = JSON.stringify(previewProps);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(exportSnippet);
      setExportMsg("Copied to clipboard");
      setTimeout(() => setExportMsg(null), 2500);
    } catch {
      setExportMsg("Copy failed");
    }
  }, [exportSnippet]);

  return (
    <div className="flex flex-1 overflow-hidden">
      <aside className="w-64 border-r border-slate-800 p-4 overflow-y-auto bg-slate-900 shadow-xl z-10 shrink-0">
        <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">
          Components
        </h2>
        <div className="flex flex-col gap-2">
          {vislabRegistry.map((e) => (
            <button
              key={e.id}
              type="button"
              onClick={() => setSelectedId(e.id)}
              className={`p-3 rounded-lg text-left transition-all border ${
                e.id === selectedId
                  ? "bg-slate-800 border-blue-500/50 ring-1 ring-blue-500/30"
                  : "bg-slate-800/50 border-slate-700/50 hover:bg-slate-700/80"
              }`}
            >
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-medium text-slate-200">
                  {e.displayName}
                </span>
                <span
                  className={`text-[9px] uppercase tracking-wide px-1.5 py-0.5 rounded border ${
                    e.maturity === "flagship"
                      ? "border-cyan-500/50 text-cyan-300 bg-cyan-500/10"
                      : "border-amber-500/40 text-amber-200/90 bg-amber-500/10"
                  }`}
                >
                  {e.maturity === "flagship" ? "flagship" : "beta"}
                </span>
              </div>
              <div className="text-xs text-slate-500 mt-1 font-mono">
                {e.globalName}
              </div>
              <div className="text-[10px] uppercase text-slate-600 mt-1">
                {e.category}
              </div>
            </button>
          ))}
        </div>
      </aside>

      <section className="flex-1 p-8 overflow-y-auto bg-[#0a0f1c] flex flex-col relative items-center justify-start">
        <div className="absolute inset-0 pattern-dots text-slate-800 opacity-50 z-0 pointer-events-none" />
        <div className="z-10 w-full max-w-4xl shadow-2xl ring-1 ring-slate-800/50 rounded-xl overflow-hidden bg-slate-900 min-h-[400px]">
          {entry ? (
            <VislabMount
              key={entry.id + propsKey}
              component={entry.globalName}
              {...previewProps}
            />
          ) : (
            <div className="p-8 text-slate-500">Select a component</div>
          )}
        </div>
      </section>

      <aside className="w-80 border-l border-slate-800 p-4 overflow-y-auto bg-slate-900 shadow-xl z-10 shrink-0 flex flex-col gap-4">
        <div>
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">
            Properties
          </h2>
          {entry?.description && (
            <p className="text-xs text-slate-500 mb-4 leading-relaxed">
              {entry.description}
            </p>
          )}
          <div className="flex flex-col gap-3">
            {entry?.props?.map((schema) => (
              <PropertyField
                key={schema.name}
                schema={schema}
                value={propValues[schema.name]}
                onChange={(v) =>
                  setPropValues((prev) => ({ ...prev, [schema.name]: v }))
                }
              />
            ))}
          </div>
          <div className="text-xs font-mono text-slate-500 break-all mt-4">
            &lt;{entry?.customElementTag} /&gt;
          </div>
        </div>

        <div>
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-2">
            Export
          </h2>
          <div className="flex gap-1 mb-2 flex-wrap">
            {(["mdx", "html", "jekyll", "iframe"] as ExportTab[]).map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => setExportTab(tab)}
                className={`px-2 py-1 text-xs rounded border ${
                  exportTab === tab
                    ? "bg-blue-600 border-blue-500 text-white"
                    : "border-slate-700 text-slate-400 hover:bg-slate-800"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
          <pre className="text-[10px] font-mono text-slate-400 bg-slate-950 border border-slate-800 rounded p-2 overflow-x-auto max-h-40 whitespace-pre-wrap">
            {exportSnippet}
          </pre>
          <button
            type="button"
            onClick={handleCopy}
            className="mt-2 w-full bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-md font-medium transition-colors text-sm"
          >
            Copy {exportTab.toUpperCase()}
          </button>
          {exportMsg && (
            <p className="mt-2 text-xs text-emerald-400">{exportMsg}</p>
          )}
        </div>
      </aside>
    </div>
  );
}
