#!/usr/bin/env node
/**
 * Compute SRI hashes for built IIFE embed bundles.
 * Run after: pnpm run build
 *
 * Writes: dist/vislab-sri.json and prints markdown for docs.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const files = [
  {
    label: "VisLabEmbeds IIFE (vislab-embed.min.js source)",
    path: "packages/web-components/dist/index.global.js",
    publishAs: "vislab-embed.min.js",
  },
  {
    label: "VisLab IIFE",
    path: "packages/components/dist/index.global.js",
    publishAs: "vislab.min.js",
  },
];

const out = [];
for (const f of files) {
  const full = join(root, f.path);
  if (!existsSync(full)) {
    console.error("Missing", f.path, "— run pnpm run build first");
    process.exit(1);
  }
  const buf = readFileSync(full);
  const hash = createHash("sha384").update(buf).digest("base64");
  const integrity = `sha384-${hash}`;
  out.push({ ...f, integrity, bytes: buf.length });
  console.log(`${f.publishAs}: ${integrity} (${buf.length} bytes raw)`);
}

const distDir = join(root, "dist");
mkdirSync(distDir, { recursive: true });
const jsonPath = join(distDir, "vislab-sri.json");
writeFileSync(jsonPath, JSON.stringify(out, null, 2) + "\n");

const md = `# Subresource Integrity (SRI)

Generated by \`node scripts/compute-sri.mjs\` after \`pnpm run build\`.
Recalculate on every release.

| File | Integrity | Raw bytes |
| ---- | --------- | --------: |
${out.map((o) => `| \`${o.publishAs}\` | \`${o.integrity}\` | ${o.bytes} |`).join("\n")}

## HTML example

\`\`\`html
<script
  src="https://cdn.example.com/vislab/vislab-embed.min.js"
  integrity="${out.find((o) => o.publishAs === "vislab-embed.min.js")?.integrity ?? "sha384-…"}"
  crossorigin="anonymous"
  defer
></script>
\`\`\`

> Replace \`cdn.example.com\` with your host. Until packages are published, serve
> files from \`pnpm --filter @vislab/cli exec vislab build -o ./public/vislab\`.
`;

writeFileSync(join(root, "docs/SRI.md"), md);
console.log("Wrote docs/SRI.md and", jsonPath);
